version: '3.8'
services:
  dev:
    container_name: dev
    # image: nestjs-api-dev:1.0.0
    build:
      context: apps/backend
      target: development
      # dockerfile: .
    command: yarn start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # restart: unless-stopped
  # prod:
  #   container_name: nestjs_api_prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: .
  #     target: production
  #     dockerfile: apps/backend/Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
    ports:
      - 5432:5432
  db-test:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5433:5432

networks:
  nesjs-network:
