version: "3.7"
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db
      - db-test
  db:
    container_name: postgres-database
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
    ports:
      - 5432:5432
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  db-test:
    container_name: postgres-database-test
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - 5433:5432
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/test-data

networks:
  webnet:

volumes:
  pgdata: